#!/bin/sh

#API login info
apiuser='apiuser'
apipass='password'
jamfProURL="https://organization.jamfcloud.com"

#update via serial number
apiURL="JSSResource/computers/serialnumber"
MacSerial=`system_profiler SPHardwareDataType | grep 'Serial Number (system)' | awk '{print $NF}'`

department=$(curl -k -H "accept: application/xml" -u $apiuser:$apipass $jamfProURL/$apiURL/$MacSerial | xmllint --xpath "string(//computer/location/department)" -)

#apiData="<computer><location><department>$getUser</department><real_name>$getRealName</real_name><department>$selectedDepartment</department></location></computer>"


#curl -k -H "Content-Type: text/json" "$jamfProURL/JSSResource/departments" --user "$apiuser:$apipass" | cut -c 18- | rev | cut -c 4- |  rev | awk -F "},{" '{ for (i=1;i<= NF; i++)print $i }' | awk -F ":" '{print $3}'
 
loggedInUser=$(stat -f %Su /dev/console)
realName=$(curl -k -H "accept: application/xml" -u $apiuser:$apipass $jamfProURL/$apiURL/$MacSerial | xmllint --xpath "string(//computer/location/realname)" -)
firstName="$(echo $realName | awk '{print $1}')"
lastName="$(echo $realName | awk '{print $2}')"
#firstInitial="$(echo $userRealName | head -c 1)"
serialNumber=$(system_profiler SPHardwareDataType | awk '/Serial/ {print $4}')

if [[ $department = "WestCap" ]]
then
	echo "Department is WestCap"
	scutil --set ComputerName WC-$firstName$lastName-$serialNumber
elif [[ $department = "CoLab" ]]
then
	echo "Department is CoLab"
	scutil --set ComputerName CL-$firstName$lastName-$serialNumber
elif [[ $department = "Venture Science" ]]
then
	echo "Department is Venture Science"
	scutil --set ComputerName VS-$firstName$lastName-$serialNumber
else
   	echo "No Department in computer record"
    scutil --set ComputerName DeptNeeded-$firstName$lastName-$serialNumber
fi

computerName=$(scutil --get ComputerName)
echo "Setting computer name to $computerName"

# Set in JAMF Computer Record
/usr/local/bin/jamf recon setComputerName -name $computerName
