#!/bin/zsh

# Check if the system is running macOS
if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "This script is only compatible with macOS."
  exit 1
fi

timeServer=$4

# Enable Location Services
sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locationd.plist

# Set the time server to pool.ntp.org
sudo systemsetup -setnetworktimeserver "$timeServer"

# Enable network time synchronization
sudo systemsetup -setusingnetworktime on

# Display the updated time server setting
echo "Time server set to: $(sudo systemsetup -getnetworktimeserver)"

# Update the system clock
sudo sntp -sS $timeServer

echo "Location Services and time server configuration completed."